### ISSUE TITLE
Bump container base OS to CentOS 9

### ISSUE THREAD

**Issue by haoming29** [PelicanPlatform/pelican#1274] opened 2024-05-10 22:45 UTC
As @aowen-uwmad pointed out, we currently uses CentOS 8 as the OS for containers, which is EOL. We should bump the OS version to EL9, if there's no blockers.

**Comment by bbockelm** [comment] 2024-05-12 19:54
Closing as duplicate of #1199.

**Closed by bbockelm** 2024-05-12 19:54 UTC
Labels: infrastructure, container
