### ISSUE TITLE
Non-recursive, direct-read `object get` on a directory yields a bogus HTML file

### ISSUE THREAD

**Issue by brianaydemir** [PelicanPlatform/pelican#1823] opened 2024-12-12 14:52 UTC
```
pelican object get pelican://federation/prefix/some_directory?directread local_file.txt
```

populates `local_file.txt` with an HTML page that appears to list the contents of `some_directory` (the footer of this page suggests that XRootD produced it), and importantly, does **not** otherwise return an error.

As this issue's title suggest, this behavior manifests in very specific circumstances:

* An `object get` on a directory that goes through a cache returns an error.
* A recursive `object get` on a directory will recurse into the directory (modulo #1820, perhaps).

**Comment by Saartank** [comment] 2024-12-12 22:54
Duplicate of #1706

**Closed** 2024-12-12 23:04 UTC
Labels: bug, client, origin
