### ISSUE TITLE
Improve support for using TLS certs/keys mounted with Kubernetes

### ISSUE THREAD

**Issue by williamnswanson** [PelicanPlatform/pelican#489] opened 2023-12-12 15:50 UTC
XRootD requires key to be owned by the xrootd user and with very specific ownership. Kubernetes doesn’t really allow us to both mount with specific ownership/permissions and automatically pass through updates from external sources so we need Pelican (or the container) to take a source cert/key and copy them to a destination with fixed ownership/permissions (both periodically and at startup)

If Pelican finds appropriate and valid certs/keys, that it can read or write, in the location where it is looking for certs/keys, could it handle the necessary intermediate steps to allow xrootd to use them (including after key/cert updates)?

Notes here
https://docs.google.com/document/d/1L7BUnROiJ-nv55vjHacwb__fB87VCCzUj02D8Sl1xpA/edit

**Comment by williamnswanson** [comment] 2023-12-12 15:51
Filed at the request of Brian B

**Comment by brianhlin** [comment] 2023-12-12 22:53
I wasn't able to repro so I must've been mixing up my environment. Closing for now

**Comment by brianhlin** [comment] 2023-12-13 15:30
@williamnswanson let's update this issue as we can't reproduce the bug but there are still annoyances in Kubernetes deployments. Please change the subject to something like "Improve support for TLS cert/key in Kubernetes environments" and go ahead and update the description with a fully fleshed out request (go ahead and use my bullet point from the notes as a starting point).

**Comment by bbockelm** [comment] 2024-01-07 18:50
This should be fixed by #569, which makes a copy of the Kubernetes-provided certificates.

**Closed by bbockelm** 2024-01-07 18:50 UTC
Labels: enhancement
