### ISSUE TITLE
Origin production container hangs at the first start up

### ISSUE THREAD

**Issue by haoming29** [PelicanPlatform/pelican#1088] opened 2024-04-10 14:45 UTC
When I run the origin production container for the first time, I got

```console
Initializing run environment for Pelican...
```

And the container hangs. If I restart the container, the initialization runs pretty fast and I can get the origin running.

The command I used to run the origin container:

```bash
docker run -it --platform linux/amd64 -p 8444:8444 -v ~/Documents/dev/pelican-docker-mount:/tmp/pelican  hub.opensciencegrid.org/pelican_platform/origin:latest serve
```

Note that the extra flags are not included (but shouldn't affect what the initialization process is doing)

**Comment by joereuss12** [comment] 2024-05-01 20:31
When trying to reproduce this myself I did not run into this issue at all. After talking with @haoming29 he tested this out again and he also did not run into the issue. We both feel it was possibly some random docker failure Haoming was experiencing on his machine. Either way, closing this as wontfix since it seems to not be an issue.

**Closed by joereuss12** 2024-05-01 20:31 UTC
Labels: wontfix
